## R script for Figure 4

library(data.table)
library(stringi)
library(stringr)
library(ggplot2)
library(biomaRt)
library(forcats)
library(tidyverse)
library(grid)
library(cowplot)
library(ggrepel)
library(readr)
library(dplyr)
library(pheatmap)
library(viridis)
library(RColorBrewer)
library(hrbrthemes)

setwd("/g/korbel/zafferani/MicroExonator/data_analysis")

################################################################################
## process raw output returned from AS workflow (see Suppl. Methods) 
################################################################################

patients <- c('P8',
              'P12',
              'P2',
              'P6',
              'P10',
              'P59',
              'P41',
              'P63',
              'P7',
              'P3',
              'P1')


#load ensembl gene id table
mart <- useEnsembl(biomart = "ensembl", dataset = "hsapiens_gene_ensembl",verbose = T)

for (patient in patients){
    
    # create output directory for each patient
    if (!file.exists(patient)){
        dir.create(patient)
    }
    
    # load info from metadata table (generated by the user before running the AS workflow)
    run_medatada <- fread(paste0("/g/korbel/zafferani/MicroExonator/",patient,"/run_metadata.tsv"))
    
    # load all raw output files from the AS analysis
    path_diff <- paste0("/g/korbel/zafferani/MicroExonator/",patient,"/Sig_nodes")
    diff_files <- list.files(path=path_diff, pattern = "*.txt",full.names = T )
    
    # merge all files in a single table
    total_delta <- rbindlist(lapply(diff_files, fread), idcol = "origin")
    total_delta[, file := factor(origin, labels = basename(diff_files))]
    total_delta[, Compare_ID:=str_replace(file, ".txt", "")]
    total_delta <- merge(total_delta, run_medatada[ , .(Compare_ID, A.cluster_names, B.cluster_names)], by="Compare_ID",allow.cartesian = T)
    total_delta <- total_delta[Compare_ID %in% run_medatada$Compare_ID, ]
    
    ### filter out non-significant events (See Suppl. Methods)
    total_delta[ (Probability.mean)==1 & is.na(cdf.beta) & Probability.var==0 & Number>40, `:=`(diff="TRUE", Diff=1) ]
    total_delta.true<- total_delta[diff==T,]
    
    # associate gene name to gene ID of AS events
    gene_table <- data.table(getBM(attributes=c('ensembl_gene_id', "hgnc_symbol", "wikigene_description"),filters = 'ensembl_gene_id', values = total_delta.true$Gene , mart))
    total_delta.gene <-  merge(total_delta.true, gene_table, by.x="Gene", by.y="ensembl_gene_id")
    total_delta.gene$gene_node<-ifelse(total_delta.gene$hgnc_symbol=='',
                                       paste(total_delta.gene$Gene,total_delta.gene$Node,sep='_'),
                                       paste(total_delta.gene$hgnc_symbol,total_delta.gene$Node,sep='_'))
    
    ## save output for later
    write_tsv(total_delta,file = paste0(patient,'/total_AS_',patient,'.tsv'), quote = 'none')
    write_tsv(total_delta.gene,file = paste0(patient,'/total_TRUE_AS_',patient,'.tsv'), quote='none')
    
}

  #############################
 #### plotting Figure 4b ####
###########################

## keep only significant events that involved the stem-like cluster

P1<-read_tsv('P1/total_TRUE_AS_P1.tsv')
P1<-subset(P1,sapply(Compare_ID, FUN=function(x) 'Cluster_2' %in% strsplit(x,'_vs_')[[1]]))
P1$Compare_ID<-factor(P1$Compare_ID)
P1<-P1[!duplicated(P1$Coord, fromLast = T),]
P1$origin='P1'

P2<-read_tsv('P2/total_TRUE_AS_P2.tsv')
P2<-subset(P2,sapply(Compare_ID, FUN=function(x) 'Cluster_2' %in% strsplit(x,'_vs_')[[1]]))
P2$Compare_ID<-factor(P2$Compare_ID)
P2<-P2[!duplicated(P2$Coord, fromLast = T),]
P2$origin='P2'

P3<-read_tsv('P3/total_TRUE_AS_P3.tsv')
P3<-subset(P3,sapply(Compare_ID, FUN=function(x) 'Cluster_2' %in% strsplit(x,'_vs_')[[1]]))
P3$Compare_ID<-factor(P3$Compare_ID)
P3<-P3[!duplicated(P3$Coord, fromLast = T),]
P3$origin='P3'

P6<-read_tsv('P6/total_TRUE_AS_P6.tsv')
P6<-subset(P6,sapply(Compare_ID, FUN=function(x) 'Cluster_3' %in% strsplit(x,'_vs_')[[1]]))
P6$Compare_ID<-factor(P6$Compare_ID)
P6<-P6[!duplicated(P6$Coord, fromLast = T),]
P6$origin='P6'

P7<-read_tsv('P7/total_TRUE_AS_P7.tsv')
P7<-subset(P7,sapply(Compare_ID, FUN=function(x) 'Cluster_1' %in% strsplit(x,'_vs_')[[1]]))
P7$Compare_ID<-factor(P7$Compare_ID)
P7<-P7[!duplicated(P7$Coord, fromLast = T),]
P7$origin='P7'

P8<-read_tsv('P8/total_TRUE_AS_P8.tsv')
P8<-subset(P8,sapply(Compare_ID, FUN=function(x) 'Cluster_2' %in% strsplit(x,'_vs_')[[1]]))
P8$Compare_ID<-factor(P8$Compare_ID)
P8<-P8[!duplicated(P8$Coord, fromLast = T),]
P8$origin='P8'

P10<-read_tsv('P10/total_TRUE_AS_P10.tsv')
P10<-subset(P10,sapply(Compare_ID, FUN=function(x) 'Cluster_2' %in% strsplit(x,'_vs_')[[1]]))
P10$Compare_ID<-factor(P10$Compare_ID)
P10<-P10[!duplicated(P10$Coord, fromLast = T),]
P10$origin='P10'

P12<-read_tsv('P12/total_TRUE_AS_P12.tsv')
P12<-subset(P12,sapply(Compare_ID, FUN=function(x) 'Cluster_2' %in% strsplit(x,'_vs_')[[1]]))
P12$Compare_ID<-factor(P12$Compare_ID)
P12<-P12[!duplicated(P12$Coord, fromLast = T),]
P12$origin='P12'

P41<-read_tsv('P41/total_TRUE_AS_P41.tsv')
P41<-subset(P41,sapply(Compare_ID, FUN=function(x) 'Cluster_2' %in% strsplit(x,'_vs_')[[1]]))
P41$Compare_ID<-factor(P41$Compare_ID)
P41<-P41[!duplicated(P41$Coord, fromLast = T),]
P41$origin='P41'

P59<-read_tsv('P59/total_TRUE_AS_P59.tsv')
P59<-subset(P59,sapply(Compare_ID, FUN=function(x) 'Cluster_3' %in% strsplit(x,'_vs_')[[1]]))
P59$Compare_ID<-factor(P59$Compare_ID)
P59<-P59[!duplicated(P59$Coord, fromLast = T),]
P59$origin='P59'

P63<-read_tsv('P63/total_TRUE_AS_P63.tsv')
P63<-subset(P63,sapply(Compare_ID, FUN=function(x) 'Cluster_0' %in% strsplit(x,'_vs_')[[1]]))
P63$Compare_ID<-factor(P63$Compare_ID)
P63<-P63[!duplicated(P63$Coord, fromLast = T),]
P63$origin='P63'

## merge into a single table
df<-rbind(P1,P2,P3,P6,P7,P8,P10,P12,P41,P59,P63)
df$Type<-factor(df$Type)

# save table (Supplementary Table 5)
write_tsv(df,'total_stem_likePatients_TRUE_AS_events.tsv',quote='none')

# group events based on their type
df_plot <- df %>% group_by(origin,Type) %>% count()
df_plot$origin<-factor(df_plot$origin,
                       levels = rev(c('P12','P8','P10','P2','P63','P59','P6','P41','P3','P7','P1')),
                       ordered = T)

# Figure 4b
png('Figure_4b.png',height = 5500, width = 4000, res = 600, type="cairo")
ggplot(df_plot,
       aes(y=origin, x = n, fill=Type),position = position_stack(reverse = T)) + 
    annotate("rect", xmin = -Inf, xmax = Inf, ymin = 3.5, ymax = Inf, fill = "#E7AD08", alpha = 0.3) + 
    annotate("rect", xmin = -Inf, xmax = Inf, ymin = 2.5, ymax = 3.5, fill = "#1B9E77", alpha = 0.3) +
    annotate("rect", xmin = -Inf, xmax = Inf, ymin = 1.5, ymax = 2.5, fill = "#E7298A", alpha = 0.3) +
    annotate("rect", xmin = -Inf, xmax = Inf, ymin = -Inf, ymax = 1.5, fill = "#DA6207", alpha = 0.3) +
    
    geom_col() + theme_classic()+ labs(y='',x='counts')+ ggtitle('AS events in stem-like population')+
    scale_y_discrete( expand=c(0.1,0.1))+
    scale_x_continuous(limits = c(0, 450), expand = c(0.01, 0))+
    guides(fill=guide_legend(title='AS type'))+ 
    theme(plot.title = element_text(hjust = 0.5,size=20, face='bold'),
          axis.text.x = element_text(color = "black",size=16),
          axis.text.y = element_text(color = "black",size=16),
          axis.title.x = element_text(size=16),
          legend.title = element_text(size=16),
          legend.text = element_text(size=14))

dev.off()



  #############################
 #### plotting Figure 4c ####
###########################

df<-read_tsv('total_stem_likePatients_TRUE_AS_events.tsv')

df <- subset(df, subset = ! is.na(hgnc_symbol))
df<- subset(df, select=c('hgnc_symbol','origin'))
df<-unique(df)
## create matrix where each gene is either 1 (AS in this patient) or 0 (not AS in this patient)
mat<-as.matrix(table(df)) 

# count appearances of the same gene across patients
row_sums<-apply(mat,1,sum)
row_sums<-sort(row_sums,decreasing = T)

# save table
write.table(row_sums, 'frequencies_AS_genes_StemlikePatients.tsv')

# keep only AS genes shared in at least 2 patients
only_2<-which(row_sums>=2)
only_2<-labels(row_sums[only_2])
only2_mat <- mat[only_2,]

#relevant pathways taken from GO analysis
splicing  <- c("RBM5", "TRA2A", "RBM3", "DDX39B", "HNRNPU", "SRSF7", "HNRNPA1", "DDX17", "HNRNPH1", "DDX39A", "SRSF10", "SRRM2", "CIRBP", "HNRNPD", "FUS", "HSPA8", "RBM39", "DDX5")
translation<-c("EIF4A2", "EIF4A1", "RPL32", "RPL10", "RPL27A", "RPLP0", "RPL13A", "RPS24", "PKM", "HNRNPD", "HNRNPU", "YBX3", "PKM", "HNRNPD", "HNRNPU", "YBX3", "EIF4A2", "RBM3", "EIF5", "RPL10", "HNRNPD", "CIRBP", "RPL13A", "EIF4G2")
stem_proliferation<-c('PTPRC','KDM1A','HNRNPU',"FOS")
adhesion <- c('RIPOR2','ADGRG1','P4HB','CYTH1','LCK','WNK1','AKT1','NOTCH1')

## genes to be annotated on the heatmap
g=c('RPL27A','RPL32','HNRNPH1','MYB','FOS','PTPRC','LCK','BRD2')
row_labs=sapply(only_2, function(x) ifelse(x %in% g ,paste0('―',x),''))
annotation_row<-sapply( only_2, function(x) ifelse(x %in% stem_proliferation,
                        'Stem cell proliferation', ifelse(x %in% splicing, 'mRNA Processing',
                        ifelse(x %in% adhesion, 'Cell-Cell Adhesion',ifelse(x %in% translation, 'Translation','other')))))

## add patients metadata to plot
annotation_col<-data.frame(Subtype=factor(c('NKX2','TAL1','TAL1','TAL1','HOXA','TAL1','TAL1','TAL1','TAL1','TLX1/3','TAL1'),ordered = T,levels = c('TAL1','NKX2','HOXA','TLX1/3')))
annotation_col$Disease<-c("Rel", "Rel" ,"Rel" ,"Rel", "Rel", "Non-Rel" ,"Non-Rel" ,"Rel","Non-Rel","Rel" ,"Rel")
row.names(annotation_col)<-colnames(only2_mat)
row_df <- data.frame(Function=annotation_row)
row_df$Function <- factor(row_df$Function, c('Translation','mRNA Processing','Cell-Cell Adhesion','Stem cell proliferation','other'))

#save table
write.table(row_df,'only_2_list_of_genes_shared_stemlike_patients.tsv',sep='\t')

only2_mat_ordered<-only2_mat[,c('P41','P59','P63','P2','P6','P8','P10','P12','P1','P3','P7')]


# Figure 4c
png(filename = '../../Paper_scripts/Figure_4c.png',width = 5000,height = 6000,res = 600, type="cairo")

pheatmap(only2_mat_ordered, cluster_cols = F, cluster_rows = T, clustering_distance_rows = 'euclidean',
         #clustering_distance_cols = 'binary',
         show_rownames = T, border_color = F,
         color=c("magenta4","yellow1"),   #rev(brewer.pal(n = 8, name ="Greys"))[c(7,1)],
         #color= c("lightgray","black"), #viridis(2),
         cellwidth = 27, cellheight = 4, legend = F,
         treeheight_row = 0,
         treeheight_col = 15,
         angle_col = 0,
         labels_row = row_labs,
         annotation_row = row_df,
         annotation_col = annotation_col,
         annotation_colors = list(Disease=c(Rel='gray',`Non-Rel`='#738595'),
                                  Subtype=c(`TLX1/3`='#E7298A',TAL1='#E7AD08',HOXA='#1B9E77',NKX2='#DA6207'),
                                  Function = c( `mRNA Processing` ="salmon1", `Translation` ="wheat3",`Cell-Cell Adhesion`='green',
                                                `Stem cell proliferation`='skyblue', other='#EAEAEA')),
         annotation_names_row = F,
         annotation_names_col = F,
         fontsize_col = 12,
         fontsize_row = 10
)

dev.off()


#for Figure 4d check FIGURE4.py


#############################
#### plotting Figure 4e ####
###########################

# reload all events for the 4 patients exhibiting differential splicing of RPL27A_10 and RPL27A_11

all_P2<-read.table('P2/total_AS_P2.tsv', sep='\t',header = T)
all_P6<-read.table('P6/total_AS_P6.tsv', sep='\t',header = T)
all_P8<-read.table('P8/total_AS_P8.tsv', sep='\t',header = T)
all_P12<-read.table('P12/total_AS_P12.tsv', sep='\t',header = T)

true_P2<-read.table('P2/total_TRUE_AS_P2.tsv', sep='\t',header = T)
true_P6<-read.table('P6/total_TRUE_AS_P6.tsv', sep='\t',header = T)
true_P8<-read.table('P8/total_TRUE_AS_P8.tsv', sep='\t',header = T)
true_P12<-read.table('P12/total_TRUE_AS_P12.tsv', sep='\t',header = T)

true_P2$patient<-'P2'
true_P6$patient<-'P6'
true_P8$patient<-'P8'
true_P12$patient<-'P12'

all<-rbind(all_P2, all_P6,all_P8,all_P12)
all<-all[!is.na(all[,'DeltaPsi.mean']) | !is.na(all[,'cdf.beta']),]
true<-rbind(true_P2, true_P6, true_P8, true_P12)

nodes<-c('RPL27A_10','RPL27A_11')
gene<-'RPL27A'
dots<-true[true$hgnc_symbol %in% gene, ]
#select unique events on the volcano plot
unique_df<-dots[c('442','443','1043','1044','2225','2226','3182','3183'),]


png('Figure_4e.png',width=3500,height=3000,res=600)

#Figure 4e
ggplot() +
    geom_point(data=all, aes(DeltaPsi.mean, -log10(cdf.beta+1e-90)), colour="grey", size=1) +
    geom_point(data=true , aes(DeltaPsi.mean, -log10(cdf.beta+1e-90)), colour="black",size=1 ) +
    geom_point(data=unique_df, aes(DeltaPsi.mean, -log10(cdf.beta+1e-90), color=patient),size=2 ) +
    
    theme_classic() + theme(plot.title = element_text(hjust = 0.5),
                            axis.text = element_text(size=12,color='black'),
                            axis.title = element_text(size=14,color='black'),
                            legend.text = element_text(size=14,color='black'),
                            legend.title = element_text(size=14,color='black'))+    ylim(c(0, 95))+
    labs(title='AS events in stem-like clusters',
         x= expression(paste('mean ',Delta,' ',Psi,)),
         y= "-Log10(cdf.beta)")+
    
    scale_color_manual(name = "Patients", 
                       values = c("#B79F00", "#93AA00","#619CFF",'#FF61C3')
    ) +
    
    geom_text_repel(data =unique_df,
                    aes(DeltaPsi.mean, -log10(cdf.beta+1e-90), colour=patient), 
                    nudge_y=15,
                    box.padding = 1,
                    max.overlaps = Inf,
                    vjust        = 1,
                    size=4,
                    label= unique_df$gene_node
    )

dev.off()


#############################
#### plotting Figure 4f ####
###########################

# keep all events for the 3 patients exhibiting differential splicing of FOS_9 and FOS_10

all_P10<-read.table('P10/total_AS_P10.tsv', sep='\t',header = T)
true_P10<-read_tsv('P10/total_TRUE_AS_P10.tsv')
true_P10$patient<-'P10'

all<-rbind(all_P2,all_P8,all_P10)
all<-all[!is.na(all[,'DeltaPsi.mean']) | !is.na(all[,'cdf.beta']),]

true<-rbind(true_P2, true_P8, true_P10)

nodes<-c('FOS_9','FOS_10')
gene<-'FOS'
dots<-true[true$hgnc_symbol %in% gene, ]
unique_df<-dots[- c(4,5,6,7),]

# Figure 4f
png(paste0('Figure_4f.png'),width=3500,height=3000,res=600)

ggplot() +
    geom_point(data=all, aes(DeltaPsi.mean, -log10(cdf.beta+1e-90)), colour="grey", size=1) +
    geom_point(data=true , aes(DeltaPsi.mean, -log10(cdf.beta+1e-90)), colour="black",size=1 ) +
    geom_point(data=unique_df, aes(DeltaPsi.mean, -log10(cdf.beta+1e-90), color=patient),size=2 ) +
    
    theme_classic() + theme(plot.title = element_text(hjust = 0.5),
                            axis.text = element_text(size=12,color='black'),
                            axis.title = element_text(size=14,color='black'),
                            legend.text = element_text(size=14,color='black'),
                            legend.title = element_text(size=14,color='black') )+
    ylim(c(0, 95))+
    labs(title='AS events in stem-like clusters',
         x= expression(paste('mean ',Delta,' ',Psi)),
         y= "-Log10(cdf.beta)")+
    
    scale_color_manual(name = "Patients", 
                       values = c("#E88526", "#93AA00","#FF61C3")
    ) +
    
    geom_text_repel(data =unique_df,
                    aes(DeltaPsi.mean, -log10(cdf.beta+1e-90), colour=patient), 
                    nudge_y=10,
                    box.padding = 1,
                    max.overlaps = Inf,
                    vjust        = 1,
                    size=4,
                    label= unique_df$gene_node
    )

dev.off()


########################################
#### plotting Figure 4g (boxplots) ####
#####################################


# define AS event
g_n<-'RPL27A_10'

#check always which cluster number corresponds to the LSCs

###################### P2 #####################################
P2_meta<-read_tsv('../P2/local_samples.tsv')
P2_meta$new_cl<-ifelse(P2_meta$cluster==2, 'Stem-like','rest')
P2_meta$patient<-'P2'
P2_psi<-read_tsv(paste0('P2_psi/psi_',g_n,'_sorted.tsv'),col_names = c('file',paste0('psi_',g_n)))
P2_psi$cell<-sapply(P2_psi$file,function(x) strsplit(x,'.psi.gz')[[1]][1])
P2_merge<-merge(P2_meta,P2_psi,by.x = 'sample',by.y = 'cell')

###################### P6 #####################################
P6_meta<-read_tsv('../P6/local_samples.tsv')
P6_meta$new_cl<-ifelse(P6_meta$cluster==3, 'Stem-like','rest')
P6_meta$patient<-'P6'
P6_psi<-read_tsv(paste0('P6_psi/psi_',g_n,'_sorted.tsv'),col_names = c('file',paste0('psi_',g_n)))
P6_psi$cell<-sapply(P6_psi$file,function(x) strsplit(x,'.psi.gz')[[1]][1])
P6_merge<-merge(P6_meta,P6_psi,by.x = 'sample',by.y = 'cell')


###################### P8 #####################################
P8_meta<-read_tsv('../P8/local_samples.tsv')
P8_meta$new_cl<-ifelse(P8_meta$cluster==2, 'Stem-like','rest')
P8_meta$patient<-'P8'
P8_psi<-read_tsv(paste0('P8_psi/psi_',g_n,'_sorted.tsv'),col_names = c('file',paste0('psi_',g_n)))
P8_psi$cell<-sapply(P8_psi$file,function(x) strsplit(x,'.psi.gz')[[1]][1])
P8_merge<-merge(P8_meta,P8_psi,by.x = 'sample',by.y = 'cell')


###################### P12 #####################################
P12_meta<-read_tsv('../P12/local_samples.tsv')
P12_meta$new_cl<-ifelse(P12_meta$cluster==2, 'Stem-like','rest')
P12_meta$patient<-'P12'
P12_psi<-read_tsv(paste0('P12_psi/psi_',g_n,'_sorted.tsv'),col_names = c('file',paste0('psi_',g_n)))
P12_psi$cell<-sapply(P12_psi$file,function(x) strsplit(x,'.psi.gz')[[1]][1])
P12_merge<-merge(P12_meta,P12_psi,by.x = 'sample',by.y = 'cell')


df<-rbind(P2_merge,P6_merge,P8_merge,P12_merge)

# perform statistical testing
w=wilcox.test(psi_RPL27A_10 ~ new_cl,data=df)
w$p.value

png(paste0("psi_boxplot_",g_n,'.png'),width = 3000,height = 2500,res=600)

ggplot(df, aes(x=new_cl, y=psi_RPL27A_10,color=new_cl)) +
    geom_violin(width=1,trim=T,size=1.5) +
    geom_boxplot(width=0.1, color="black", alpha=0.5) +
    theme_classic() + 
    ylim(0,1.3)+
    theme(
        legend.position="none",
        plot.title = element_text(size=20,face = 'bold',hjust = .5),
        axis.text = element_text(size=18,color='black'),
        axis.title = element_text(size=18,color='black')
    ) +
    ggtitle("RPL27A: node 10") +
    xlab("")+
    ylab("PSI")+
    scale_color_manual(values = c('orange','cornflowerblue'))+
    annotate('text',x=1.5, hjust=.5,y=1.15, size=6,label=paste0('p-val: ',format(w$p.value, scientific = T, digits = 1)))

dev.off()


#################################################################################

g_n<-'RPL27A_11'


###################### P2 #####################################
P2_meta<-read_tsv('../P2/local_samples.tsv')
P2_meta$new_cl<-ifelse(P2_meta$cluster==2, 'Stem-like','rest')
P2_meta$patient<-'P2'
P2_psi<-read_tsv(paste0('P2_psi/psi_',g_n,'_sorted.tsv'),col_names = c('file',paste0('psi_',g_n)))
P2_psi$cell<-sapply(P2_psi$file,function(x) strsplit(x,'.psi.gz')[[1]][1])
P2_merge<-merge(P2_meta,P2_psi,by.x = 'sample',by.y = 'cell')

###################### P6 #####################################
P6_meta<-read_tsv('../P6/local_samples.tsv')
P6_meta$new_cl<-ifelse(P6_meta$cluster==3, 'Stem-like','rest')
P6_meta$patient<-'P6'
P6_psi<-read_tsv(paste0('P6_psi/psi_',g_n,'_sorted.tsv'),col_names = c('file',paste0('psi_',g_n)))
P6_psi$cell<-sapply(P6_psi$file,function(x) strsplit(x,'.psi.gz')[[1]][1])
P6_merge<-merge(P6_meta,P6_psi,by.x = 'sample',by.y = 'cell')


###################### P8 #####################################
P8_meta<-read_tsv('../P8/local_samples.tsv')
P8_meta$new_cl<-ifelse(P8_meta$cluster==2, 'Stem-like','rest')
P8_meta$patient<-'P8'
P8_psi<-read_tsv(paste0('P8_psi/psi_',g_n,'_sorted.tsv'),col_names = c('file',paste0('psi_',g_n)))
P8_psi$cell<-sapply(P8_psi$file,function(x) strsplit(x,'.psi.gz')[[1]][1])
P8_merge<-merge(P8_meta,P8_psi,by.x = 'sample',by.y = 'cell')


###################### P12 #####################################
P12_meta<-read_tsv('../P12/local_samples.tsv')
P12_meta$new_cl<-ifelse(P12_meta$cluster==2, 'Stem-like','rest')
P12_meta$patient<-'P12'
P12_psi<-read_tsv(paste0('P12_psi/psi_',g_n,'_sorted.tsv'),col_names = c('file',paste0('psi_',g_n)))
P12_psi$cell<-sapply(P12_psi$file,function(x) strsplit(x,'.psi.gz')[[1]][1])
P12_merge<-merge(P12_meta,P12_psi,by.x = 'sample',by.y = 'cell')


df1<-rbind(P2_merge,P6_merge,P8_merge,P12_merge)

# perform statistical testing
w=wilcox.test(psi_RPL27A_11 ~ new_cl,data=df)
w$p.value

png(paste0("psi_boxplot_",g_n,'.png'),width = 3000,height = 2500,res=600)

ggplot(df, aes(x=new_cl, y=psi_RPL27A_11,color=new_cl)) +
    geom_violin(width=1,trim=T,size=1.5) +
    geom_boxplot(width=0.1, color="black", alpha=0.5) +
    theme_classic() + 
    ylim(0,1.3)+
    theme(
        legend.position="none",
        plot.title = element_text(size=20,face = 'bold',hjust = .5),
        axis.text = element_text(size=18,color='black'),
        axis.title = element_text(size=18,color='black')
    ) +
    ggtitle("RPL27A: node 11") +
    xlab("")+
    ylab("PSI")+
    scale_color_manual(values = c('orange','cornflowerblue'))+
    annotate('text',x=1.5, hjust=.5,y=1.15, size=6,label=paste0('p-val: ',format(w$p.value, scientific = T, digits = 1)))

dev.off()


########################################
#### plotting Figure 4h (boxplots) ####
#####################################


g_n<-'FOS_9'

###################### P2 #####################################
P2_meta<-read_tsv('../P2/local_samples.tsv')
P2_meta$new_cl<-ifelse(P2_meta$cluster==2, 'Stem-like','rest')
P2_meta$patient<-'P2'
P2_psi<-read_tsv(paste0('P2_psi/psi_',g_n,'_sorted.tsv'),col_names = c('file',paste0('psi_',g_n)))
P2_psi$cell<-sapply(P2_psi$file,function(x) strsplit(x,'.psi.gz')[[1]][1])
P2_merge<-merge(P2_meta,P2_psi,by.x = 'sample',by.y = 'cell')


###################### P8 #####################################
P8_meta<-read_tsv('../P8/local_samples.tsv')
P8_meta$new_cl<-ifelse(P8_meta$cluster==2, 'Stem-like','rest')
P8_meta$patient<-'P8'
P8_psi<-read_tsv(paste0('P8_psi/psi_',g_n,'_sorted.tsv'),col_names = c('file',paste0('psi_',g_n)))
P8_psi$cell<-sapply(P8_psi$file,function(x) strsplit(x,'.psi.gz')[[1]][1])
P8_merge<-merge(P8_meta,P8_psi,by.x = 'sample',by.y = 'cell')


###################### P10 #####################################
P10_meta<-read_tsv('../P10/local_samples.tsv')
P10_meta$new_cl<-ifelse(P10_meta$cluster==2, 'Stem-like','rest')
P10_meta$patient<-'P10'
P10_psi<-read_tsv(paste0('P10_psi/psi_',g_n,'_sorted.tsv'),col_names = c('file',paste0('psi_',g_n)))
P10_psi$cell<-sapply(P10_psi$file,function(x) strsplit(x,'.psi.gz')[[1]][1])
P10_merge<-merge(P10_meta,P10_psi,by.x = 'sample',by.y = 'cell')


df<-rbind(P2_merge,P8_merge,P10_merge)
# perform statistical testing
w=wilcox.test(psi_FOS_9 ~ new_cl,data=df)
w$p.value

png(paste0("psi_boxplot_",g_n,'.png'),width = 3000,height = 2500,res=600)

ggplot(df, aes(x=new_cl, y=psi_FOS_9,color=new_cl)) +
    geom_violin(width=1,trim=T,size=1.5) +
    geom_boxplot(width=0.1, color="black", alpha=0.5) +
    #scale_fill_viridis(discrete = TRUE) +
    theme_classic() + ylim(0,1.3)+
    theme(  legend.position="none",
            plot.title = element_text(size=20,face = 'bold',hjust = .5),
            axis.text = element_text(size=18,color='black'),
            axis.title = element_text(size=18,color='black')
    ) +
    ggtitle("FOS: node 9") +
    xlab("")+
    ylab("PSI")+
    scale_color_manual(values = c('orange','cornflowerblue'))+
    annotate('text',x=1.5, hjust=.5,y=1.15, size=6,label=paste0('p-val: ',round(w$p.value,3)))

dev.off()

###################################################################################################

g_n<-'FOS_10'

###################### P2 #####################################
P2_meta<-read_tsv('../P2/local_samples.tsv')
P2_meta$new_cl<-ifelse(P2_meta$cluster==2, 'Stem-like','rest')
P2_meta$patient<-'P2'
P2_psi<-read_tsv(paste0('P2_psi/psi_',g_n,'_sorted.tsv'),col_names = c('file',paste0('psi_',g_n)))
P2_psi$cell<-sapply(P2_psi$file,function(x) strsplit(x,'.psi.gz')[[1]][1])
P2_merge<-merge(P2_meta,P2_psi,by.x = 'sample',by.y = 'cell')


###################### P8 #####################################
P8_meta<-read_tsv('../P8/local_samples.tsv')
P8_meta$new_cl<-ifelse(P8_meta$cluster==2, 'Stem-like','rest')
P8_meta$patient<-'P8'
P8_psi<-read_tsv(paste0('P8_psi/psi_',g_n,'_sorted.tsv'),col_names = c('file',paste0('psi_',g_n)))
P8_psi$cell<-sapply(P8_psi$file,function(x) strsplit(x,'.psi.gz')[[1]][1])
P8_merge<-merge(P8_meta,P8_psi,by.x = 'sample',by.y = 'cell')


###################### P10 #####################################
P10_meta<-read_tsv('../P10/local_samples.tsv')
P10_meta$new_cl<-ifelse(P10_meta$cluster==2, 'Stem-like','rest')
P10_meta$patient<-'P10'
P10_psi<-read_tsv(paste0('P10_psi/psi_',g_n,'_sorted.tsv'),col_names = c('file',paste0('psi_',g_n)))
P10_psi$cell<-sapply(P10_psi$file,function(x) strsplit(x,'.psi.gz')[[1]][1])
P10_merge<-merge(P10_meta,P10_psi,by.x = 'sample',by.y = 'cell')


df<-rbind(P2_merge,P8_merge,P10_merge)
# perform statistical testing
w=wilcox.test(psi_FOS_10 ~ new_cl,data=df)
w$p.value

png(paste0("psi_boxplot_",g_n,'.png'),width = 3000,height = 2500,res=600)

ggplot(df, aes(x=new_cl, y=psi_FOS_10,color=new_cl)) +
    geom_violin(width=1,trim=T,size=1.5) +
    geom_boxplot(width=0.1, color="black", alpha=0.5) +
    #scale_fill_viridis(discrete = TRUE) +
    theme_classic() + ylim(0,1.3)+
    theme(  legend.position="none",
            plot.title = element_text(size=20,face = 'bold',hjust = .5),
            axis.text = element_text(size=18,color='black'),
            axis.title = element_text(size=18,color='black')
    ) +
    ggtitle("FOS: node 9") +
    xlab("")+
    ylab("PSI")+
    scale_color_manual(values = c('orange','cornflowerblue'))+
    annotate('text',x=1.5, hjust=.5,y=1.15, size=6,label=paste0('p-val: ',round(w$p.value,3)))

dev.off()


# for sashimi plots of Figure 4g and 4h check FIGURE4.sh

